
spring.application.name=order-processing-system
server.port=8080

logging.level.root=INFO
logging.level.com.cashinvoice.order=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.jackson.default-property-inclusion=non_null

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always